from typing import List, Optional
from pydantic import BaseModel, Field


class AttributeChoice(BaseModel):
    id: Optional[int] = Field(alias="ID")
    name: Optional[str] = Field(alias="Name")
    is_active: Optional[bool] = Field(alias="IsActive")
    date_created: Optional[str] = Field(alias="DateCreated")
    date_modified: Optional[str] = Field(alias="DateModified")
    order: Optional[int] = Field(alias="Order")


class Attribute(BaseModel):
    id: Optional[int] = Field(alias="ID")
    name: Optional[str] = Field(alias="Name")
    order: Optional[int] = Field(alias="Order")
    description: Optional[str] = Field(alias="Description")
    section_id: Optional[int] = Field(alias="SectionID")
    section_name: Optional[str] = Field(alias="SectionName")
    field_type: Optional[str] = Field(alias="FieldType")
    data_type: Optional[str] = Field(alias="DataType")
    choices: Optional[List[AttributeChoice]] = Field(alias="Choices")
    is_required: Optional[bool] = Field(alias="IsRequired")
    is_updatable: Optional[bool] = Field(alias="IsUpdatable")
    value: Optional[str] = Field(alias="Value")
    value_text: Optional[str] = Field(alias="ValueText")
    choices_text: Optional[str] = Field(alias="ChoicesText")
    associated_item_ids: Optional[List[int]] = Field(alias="AssociatedItemIDs")


class Attachment(BaseModel):
    pass  # Define attachment fields here if needed


class AssetModel(BaseModel):
    id: Optional[int] = Field(alias="ID")
    app_id: Optional[int] = Field(alias="AppID")
    app_name: Optional[str] = Field(alias="AppName")
    form_id: Optional[int] = Field(alias="FormID")
    form_name: Optional[str] = Field(alias="FormName")
    product_model_id: Optional[int] = Field(alias="ProductModelID")
    product_model_name: Optional[str] = Field(alias="ProductModelName")
    manufacturer_id: Optional[int] = Field(alias="ManufacturerID")
    manufacturer_name: Optional[str] = Field(alias="ManufacturerName")
    supplier_id: Optional[int] = Field(alias="SupplierID")
    supplier_name: Optional[str] = Field(alias="SupplierName")
    status_id: Optional[int] = Field(alias="StatusID")
    status_name: Optional[str] = Field(alias="StatusName")
    location_id: Optional[int] = Field(alias="LocationID")
    location_name: Optional[str] = Field(alias="LocationName")
    location_room_id: Optional[int] = Field(alias="LocationRoomID")
    location_room_name: Optional[str] = Field(alias="LocationRoomName")
    tag: Optional[str] = Field(alias="Tag")
    serial_number: Optional[str] = Field(alias="SerialNumber")
    name: Optional[str] = Field(alias="Name")
    purchase_cost: Optional[float] = Field(alias="PurchaseCost")
    acquisition_date: Optional[str] = Field(alias="AcquisitionDate")
    expected_replacement_date: Optional[str] = Field(alias="ExpectedReplacementDate")
    requesting_customer_id: Optional[str] = Field(alias="RequestingCustomerID")
    requesting_customer_name: Optional[str] = Field(alias="RequestingCustomerName")
    requesting_department_id: Optional[int] = Field(alias="RequestingDepartmentID")
    requesting_department_name: Optional[str] = Field(alias="RequestingDepartmentName")
    owning_customer_id: Optional[str] = Field(alias="OwningCustomerID")
    owning_customer_name: Optional[str] = Field(alias="OwningCustomerName")
    owning_department_id: Optional[int] = Field(alias="OwningDepartmentID")
    owning_department_name: Optional[str] = Field(alias="OwningDepartmentName")
    parent_id: Optional[int] = Field(alias="ParentID")
    parent_serial_number: Optional[str] = Field(alias="ParentSerialNumber")
    parent_name: Optional[str] = Field(alias="ParentName")
    parent_tag: Optional[str] = Field(alias="ParentTag")
    maintenance_schedule_id: Optional[int] = Field(alias="MaintenanceScheduleID")
    maintenance_schedule_name: Optional[str] = Field(alias="MaintenanceScheduleName")
    configuration_item_id: Optional[int] = Field(alias="ConfigurationItemID")
    created_date: Optional[str] = Field(alias="CreatedDate")
    created_uid: Optional[str] = Field(alias="CreatedUid")
    created_full_name: Optional[str] = Field(alias="CreatedFullName")
    modified_date: Optional[str] = Field(alias="ModifiedDate")
    modified_uid: Optional[str] = Field(alias="ModifiedUid")
    modified_full_name: Optional[str] = Field(alias="ModifiedFullName")
    external_id: Optional[str] = Field(alias="ExternalID")
    external_source_id: Optional[int] = Field(alias="ExternalSourceID")
    external_source_name: Optional[str] = Field(alias="ExternalSourceName")
    attributes: Optional[List[Attribute]] = Field(alias="Attributes")
    attachments: Optional[List[Attachment]] = Field(alias="Attachments")
    uri: Optional[str] = Field(alias="Uri")
