from typing import List, Optional
from pydantic import BaseModel, Field


class Attribute(BaseModel):
    id: Optional[int] = Field(alias="ID")
    name: Optional[str] = Field(alias="Name")
    order: Optional[int] = Field(alias="Order")
    description: Optional[str] = Field(alias="Description")
    section_id: Optional[int] = Field(alias="SectionID")
    section_name: Optional[str] = Field(alias="SectionName")
    field_type: Optional[str] = Field(alias="FieldType")
    data_type: Optional[str] = Field(alias="DataType")
    choices: Optional[List[str]] = Field(alias="Choices")
    is_required: Optional[bool] = Field(alias="IsRequired")
    is_updatable: Optional[bool] = Field(alias="IsUpdatable")
    value: Optional[str] = Field(alias="Value")
    value_text: Optional[str] = Field(alias="ValueText")
    choices_text: Optional[str] = Field(alias="ChoicesText")
    associated_item_ids: Optional[List[int]] = Field(alias="AssociatedItemIDs")


class KnowledgeArticleModel(BaseModel):
    id: Optional[int] = Field(alias="ID")
    app_id: Optional[int] = Field(alias="AppID")
    app_name: Optional[str] = Field(alias="AppName")
    category_id: Optional[int] = Field(alias="CategoryID")
    category_name: Optional[str] = Field(alias="CategoryName")
    subject: Optional[str] = Field(alias="Subject")
    body: Optional[str] = Field(alias="Body")
    summary: Optional[str] = Field(alias="Summary")
    status: Optional[int] = Field(alias="Status")
    attributes: Optional[List[Attribute]] = Field(alias="Attributes")
    review_date_utc: Optional[str] = Field(alias="ReviewDateUtc")
    order: Optional[float] = Field(alias="Order")
    is_published: Optional[bool] = Field(alias="IsPublished")
    is_public: Optional[bool] = Field(alias="IsPublic")
    whitelist_groups: Optional[bool] = Field(alias="WhitelistGroups")
    inherit_permissions: Optional[bool] = Field(alias="InheritPermissions")
    notify_owner: Optional[bool] = Field(alias="NotifyOwner")
    revision_id: Optional[int] = Field(alias="RevisionID")
    revision_number: Optional[int] = Field(alias="RevisionNumber")
    draft_status: Optional[str] = Field(alias="DraftStatus")
    created_date: Optional[str] = Field(alias="CreatedDate")
    created_uid: Optional[str] = Field(alias="CreatedUid")
    created_full_name: Optional[str] = Field(alias="CreatedFullName")
    modified_date: Optional[str] = Field(alias="ModifiedDate")
    modified_uid: Optional[str] = Field(alias="ModifiedUid")
    modified_full_name: Optional[str] = Field(alias="ModifiedFullName")
    owner_uid: Optional[str] = Field(alias="OwnerUid")
    owner_full_name: Optional[str] = Field(alias="OwnerFullName")
    owning_group_id: Optional[int] = Field(alias="OwningGroupID")
    owning_group_name: Optional[str] = Field(alias="OwningGroupName")
    tags: Optional[List[str]] = Field(alias="Tags")
    attachments: Optional[List[dict]] = Field(alias="Attachments")
    uri: Optional[str] = Field(alias="Uri")
